name: on daily

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate_burndown_chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm i
      - name: Generate burndown chart
        uses: ./
        with:
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DB_BACKLOG: d7466d82ea034582b75ba81f0c168915
          NOTION_DB_SPRINT_SUMMARY: 4ad782fd356d4263aa6433d402283f84
          NOTION_DB_DAILY_SUMMARY: 87818281a4434c06b8cd6cc9e52e2163
          NOTION_PROPERTY_SPRINT: Sprint
          NOTION_PROPERTY_ESTIMATE: Estimate
          NOTION_PROPERTY_PATTERN_STATUS_EXCLUDE: Done
          INCLUDE_WEEKENDS: true
          
      - name: Commit burndown chart
        run: |
          git config --local user.email "brewer36@purdue.edu"
          git config --local user.name "nicole-brewer"
          git add ./out
          git commit -m "run: upload new burndown chart"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          force: true
